#!/usr/bin/bash

cd ../../../../
make tada68:alex:flashbin

sudo mount -t vfat -o rw,nosuid,nodev,relatime,uid=1000,gid=1000,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,showexec,utf8,flush,errors=remount-ro,uhelper=udisks2 /dev/sda /mnt/tada68
sudo cp FLASH.bin /mnt/tada68
sudo umount /mnt/tada68
